local _, ns = ...
-- Patch Notes (Settings > Patch Notes) and the What's New card read these; newest first.
-- Curated: what a player notices. Each version: new = full items (icon, title, a few
-- words, the settings page it lives on), changes / fixes = one line each.
-- client = "forever" / "anniversary" marks what only one game has; card = true puts an
-- item on the What's New card (s = its one-line short row for players updating from far
-- back); look = true is the card's NEW box; also = the card's Also line; thanks = a
-- line at the bottom of the version's Patch Notes (never on the card).
ns.PATCH_NOTES = {
	{
		v = "3.0.8",
		date = "2026-10-10",
		headline = "Settings drawn with icons, Totem Rows, Running out, and a controller bar",
		new = {
			{ h = "Proc Glow", icon = "Interface\\Icons\\Spell_Nature_Lightning",
			  b = "A third Glow Shape: Proc Glow, the game's own proc art, a ring just outside the icon. The ready glow, the alert glows and the pulse flash all follow it, with a Proc Glow Thickness slider next to it. On Ready Reminders every icon has its own Glow Shape and thickness (and Copy When Ready To All Icons carries them). Square stays the default.",
			  path = "Settings > General > Themes > Glow Shape", open = { "settings", "settings_themes" }, look = true },
			{ h = "Out Of The Way", icon = "Interface\\Icons\\INV_Misc_Map_01",
			  b = "One switch that gets ShamanPower's displays out of the way, and brings them back the moment they could matter: out of a fight, not inside a dungeon, raid or battleground, and with no enemy targeted (red or yellow), they hide, or fade to your Faded Opacity. Where: in a city or an inn only, or anywhere outside a fight. Any one of those ending brings everything back at once. Under the switch, one line per module (Ready Reminders, Shield Charges, Cooldown Bar, Totem Bar, Loadout Bar, Controller Bar, Expiring Alerts, Earth Shield Tracker, Party Buff Tracker), so you can hide it all or keep the totem bar and hide only the reminders. Off to start.",
			  path = "Settings > Appearance > Visibility > Out Of The Way", open = { "settings", "settings_town" },
			  card = true, s = "Out Of The Way: hide or fade it all outside a fight, back the moment it matters." },
			{ h = "Ready Reminders: Ready Flash has its own tab", icon = "Interface\\Icons\\Spell_Nature_Lightning",
			  b = "Ready Reminders is two tabs now: Icons (the page as it was) and Ready Flash. On the Ready Flash tab: click a spell to flash it when it is ready (an icon is not needed any more, so the Show choice Never (Ready Flash Only) is gone), one look every flash shares with a Test button, when it plays (Only For Cooldowns Over, Flash Early, and a new Only In Combat), and its spot. A spell's right-click menu there keeps only what is per spell: on or off, Flash Early, a spot of its own with its own size. Your flash settings carried over; nothing stopped flashing.",
			  path = "Settings > Alerts & Reminders > Ready Reminders > Ready Flash", open = { "fluffy", "readyflash_section" },
			  card = true, s = "Ready Flash has its own tab: click a spell to flash it, no icon needed." },
			{ h = "Ready Reminders: Weapon Set", icon = "Interface\\Icons\\INV_Shield_06",
			  b = "A new entry for tanks who swap all day: Weapon Set is always on screen and shows what you hold, with the item's own icon and a word under it: your shield (a one-hander and shield), your two-hander, your off-hand weapon (two weapons) or your weapon alone. It changes the moment you swap, in a fight too. Glow While Holding picks the set that makes it glow, so the wrong set stands out; Sound On A Swap and Ready Flash On A Swap say so the moment you change. Off to start, on both games.",
			  path = "Settings > Ready Reminders > Spells", open = { "fluffy", "readyreminders_section" },
			  card = true, s = "Weapon Set: a reminder that shows what you hold, shield or two-hander." },
			{ h = "Ready Reminders: Stormstrike's cooldown reset", icon = "Interface\\Icons\\Ability_Shaman_Stormstrike", client = "forever",
			  b = "A tank's dodge or parry resets Stormstrike's cooldown, and the reminder used to just turn ready, the same as a cooldown that ran out. Now Stormstrike's menu has When The Cooldown Resets: a gold burst round the icon (the Proc Glow ring, in your color), the word RESET over it, your Ready Flash saying Stormstrike reset!, and a sound of its own, each its own switch. The reset's sound plays in place of the Ready sound, so you never hear two. Everything off to start.",
			  path = "Ready Reminders: right-click Stormstrike > When The Cooldown Resets", open = { "fluffy", "readyreminders_section" } },
			{ h = "Ready Reminders: a buff can replace the icon", icon = "Interface\\Icons\\Ability_Shaman_Stormstrike",
			  b = "A fourth way to show a spell's buff (Improved Stormstrike and the others): Replaces The Icon. While the buff is on you, its own picture takes the spell icon's place, with its time in the corner; when it ends, the spell icon is back.",
			  path = "Ready Reminders: right-click an icon > its buff > Show The Buff", open = { "fluffy", "readyreminders_section" } },
			{ h = "Expiring Alerts: shield gone, in a fight on WoW: Forever", icon = "Interface\\Icons\\Spell_Shaman_StaticShock",
			  b = "The Lightning / Water Shield gone alert now fires in a fight on WoW: Forever too, the moment the last orb goes: the game's Cooldown Manager tells ShamanPower (your shield in its Tracked Buffs; ShamanPower sets that up for you with one reload, and hides that icon; the Set Up The Cooldown Manager switch on the Shield Charges page turns that off). Before, a shield that fell off in a fight was reported only when the fight ended.",
			  path = "Settings > Expiring Alerts", open = { "fluffy", "expiringalerts_section" } },
			{ h = "Shield Charges: When It's Gone", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "On each shield's menu: at 0 charges, or with no shield up, the icon plays a glow (in your Glow Shape and color, Proc Glow too), a pulse, or both, until a shield is up again. Each shield has its own. In a fight on WoW: Forever the game's Cooldown Manager tells ShamanPower the moment your shield goes: it needs your shield in the Cooldown Manager's Tracked Buffs (ShamanPower sets that up for you with one reload, and hides that icon; the Set Up The Cooldown Manager switch on the Shield Charges page turns that off). Also fixed: in a fight on Forever the charge bar sat over the icon instead of beside it.",
			  path = "Settings > Shield Charges: right-click a shield > When It's Gone", open = { "fluffy", "shieldcharges_section" },
			  card = true, s = "Shield Charges: When It's Gone, a glow or pulse until a shield is up again, in fights on Forever too." },
			{ h = "Ready Reminders: Weapon Imbue", icon = "Interface\\Icons\\Spell_Fire_FlameTounge",
			  b = "A new spell in the list: Weapon Imbue shows while an imbue is missing (the main hand; with two weapons, either hand), with the icon of the imbue you last had on, and lights up like any ready spell: glow, sound, flash. While your imbues are on it counts the shorter one down, or hides, as the icon's Show setting says. Off until you turn it on.",
			  path = "Settings > Ready Reminders > Spells", open = { "fluffy", "readyreminders_section" } },
			{ h = "Ready Reminders: Glow Only In Combat", icon = "Interface\\Icons\\Ability_Warrior_BattleShout",
			  b = "On each icon's When Ready menu: out of a fight the icon shows with no glow, and the glow comes when a fight starts. Off by default; Copy When Ready To All Icons carries it.",
			  path = "Ready Reminders: right-click an icon > When Ready", open = { "fluffy", "readyreminders_section" } },
			{ h = "Time Only While Running Out", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "On the cooldown bar's shield item: its time stays out of sight while there is plenty left, and shows the moment the shield is running out (your Running Out At seconds). In a fight on WoW: Forever the game draws that time itself, so it is exact to the second, not an estimate. Off to start.",
			  path = "Settings > Cooldown Bar > Effects", open = { "fluffy", "cdbar_page" } },
			{ h = "Glow While Missing", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "A switch next to Turns Red While Missing on the cooldown bar's shield and imbue items: while the shield or an imbue is gone, the button's edges glow red until you cast it again (and Proc Glow plays round it when that is your Glow Shape). In a fight on WoW: Forever the shield's glow sits under the game's shield icon, so it shows the moment the icon goes.",
			  path = "Settings > Cooldown Bar > Effects", open = { "fluffy", "cdbar_page" } },
			{ h = "Ready Reminders: Rows, and the Spells row shows your layout", icon = "Interface\\Icons\\Ability_Shaman_Stormstrike",
			  b = "Placement has a third choice, Rows: build each row yourself, as many as you want, drag spells onto them and move each row on its own, with its own spacing (0 puts icons side by side, touching) and direction. In Grid the Spells row draws your grid as it fills; in Rows it draws your rows. Drag a spell in the Spells row to change the order in every placement. Spacing left Free, where it meant nothing.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" } },
			{ h = "Settings pages drawn with icons", icon = "Interface\\Icons\\INV_Misc_Gear_01",
			  b = "The Cooldown Bar, Totem Bar, Shield Charges, Expiring Alerts, Reactive Totems, Loadouts, Coverage, Totem Range Tracker, Pop-Out Trackers and (TBC Anniversary) Raid Cooldowns pages show what they are about as a row of icons: click one to turn it on or off, right-click it for everything about it, drag it to change its place. A blue corner marks an icon with settings of its own. Search all settings still finds every setting that moved into a menu, and lands you on its row. Every page keeps Preview and Reset This Page.",
			  path = "Settings > Bars > Cooldown Bar", open = { "fluffy", "cdbar_page" },
			  card = true,
			  s = "Settings pages drawn with icons: click one to turn it on or off, right-click it for its settings." },
			{ h = "Totem Bar page: one Bar tab", icon = "Interface\\Icons\\Spell_Nature_StoneSkinTotem",
			  b = "The Bar tab opens first: the four elements in the bar's order, Drop All and (TBC Anniversary) Earth Shield, with a Totems line per element (click: in or out of its flyout). Each totem's Pulse Bar, Pulse Flash, Counts As Temporary and key live in its menu. The Items, Order, Drop All and Flyouts tabs are gone: their settings moved into the menus.",
			  path = "Settings > Bars > Totem Bar", open = { "buttons", "auto_button" } },
			{ h = "Cooldown Bar page: each item on its own", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "Every item (shields, imbues, Signature Moves) has its own settings in its menu, with Copy, Paste and Copy To. Move the Cooldown Bar is a button at the top and unlocks only the cooldown bar.",
			  path = "Settings > Bars > Cooldown Bar", open = { "fluffy", "cdbar_page" } },
			{ h = "Shield Charges page: each shield on its own", icon = "Interface\\Icons\\Ability_Shaman_WaterShield",
			  b = "Lightning Shield, Water Shield and Earth Shield each have their own settings now (spot, look, sound), and What You See shows each shield's real display in a box of its own: click it to see the charges used up and fill again.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_page" } },
			{ h = "Expiring Alerts and Reactive Totems pages", icon = "Interface\\Icons\\Spell_Nature_TremorTotem",
			  b = "A click turns one alert on or off (the old Enable Shield, Totem and Imbue Alerts switches are gone). Expiring Alerts: each totem element has its own When One Is Destroyed, When One Expires and sound, and Main Hand and Off Hand their own sound. Reactive Totems: each alert has its own look and sound.",
			  path = "Settings > Alerts & Reminders > Expiring Alerts", open = { "fluffy", "expiringalerts_section" } },
			{ h = "Loadouts page: one tile per loadout", icon = "Interface\\Icons\\INV_Misc_Note_01",
			  b = "Click a tile to switch to that loadout, right-click it to edit it, drag it to change its place, and + saves the totems on your bar as a new loadout.",
			  path = "Settings > Bars > Loadouts", open = { "buttons", "loadouts_section" } },
			{ h = "Use the Old Settings Look", icon = "Interface\\Icons\\INV_Letter_15",
			  b = "Every settings page as plain rows, as before 3.0.8, instead of a row of icons. Both looks change the same settings, so switch back any time. The first login after updating asks once whether you want it.",
			  path = "Settings > General > Main", open = { "settings", "settings_show" },
			  card = true,
			  s = "Use the Old Settings Look puts every page back to plain rows." },
			{ h = "Unlock UI: Reset asks first", icon = "Interface\\Icons\\INV_Misc_Wrench_01",
			  b = "Reset asks before it moves anything, and one box's Reset resets only that box (Ready Reminders, Ready Flash spots, Reactive Totems, Shield Charges, Coverage cells).",
			  path = "Settings > General > Main > Unlock UI", open = { "settings", "settings_show" } },
			{ h = "Totem Rows", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "Every totem of every element laid out in rows, for every style but Grid. With Show Main Totem Bar off, the rows carry the duration bar, time left, pulse, party dots and effects. Keep Flyouts on Main Totem Bar keeps the flyouts too. The rows follow your Totem Bar > Clicks settings and take your theme's looks.",
			  path = "Settings > Bars > Totem Bar > Style", open = { "settings", "settings_totemMode" },
			  card = true,
			  s = "Totem Rows: every totem of every element laid out in rows." },
			{ h = "Put Your Usual Totem Back", icon = "Interface\\Icons\\Spell_Nature_GroundingTotem",
			  b = "When a temporary totem you dropped (Tremor, Grounding, Earthbind and the like) ends, that element's button glows with BACK until your usual totem is down again. It only reminds you: it never casts anything.",
			  path = "Settings > Bars > Totem Bar > Effects", open = { "fluffy", "totembar_effects_section" },
			  card = true,
			  s = "Put Your Usual Totem Back: BACK on the button until your usual totem is down again." },
			{ h = "Faded Opacity goes down to 0%", icon = "Interface\\Icons\\Spell_Nature_WispSplode",
			  b = "In 1% steps. With Fade Instead of Hide on, a bar faded to 0% is invisible, its flyouts fade with it, and bar and flyouts come back in a fight the moment a totem drops.",
			  path = "Settings > Appearance > Visibility", open = { "settings", "settings_visibility" } },
			{ h = "Hide When No Totems comes back mid-fight", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "A fight that started with no totems used to keep the bar hidden until the fight ended (the game forbids an addon to show cast buttons in a fight). Now the bar comes back the moment a totem is down, in a fight too, and hides again when the last totem is gone. Hide Out of Combat and Show When I Have a Target still apply. Not for Grid style or Totem Rows, and not with Fade Instead of Hide (a faded bar already comes back).",
			  path = "Settings > Appearance > Visibility", open = { "settings", "settings_visibility" } },
			{ h = "Right-click clears one assignment", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "With Right-Click an Assignment set to Clear Assignment, a right-click in the assignment window clears that one totem.",
			  path = "Settings > Bars > Totem Bar > Clicks", open = { "settings", "settings_totemClicks" } },
			{ h = "Compact style: a key for Your Shield Line", icon = "Interface\\Icons\\INV_Misc_Key_03",
			  b = "In Keybind Mode, Your Shield Line takes a key and shows it like the totem lines. So does the Earth Shield line.",
			  path = "Keybind Mode (/sp bind)" },
			{ h = "Controller mode", icon = "Interface\\Icons\\INV_Gizmo_02",
			  b = "When the game is in its gamepad look, a controller totem bar: the four elements on a d-pad cross with Drop All in the middle (or rows, or a square), with rings, pulse, countdown and the game's own button glyphs. Hold LB and the d-pad drops a totem; LB + A, B, X or Y is Drop All, Recall, your shield or your imbue; LB + RB opens a totem picker (the d-pad picks, A takes it, B closes). Your cooldowns can sit on the controller bar too, or in a box of their own (Show My Cooldowns). The keyboard totem bar and cooldown bar hide while the controller look shows (both can be turned off). Rumble is optional. Automatic to start: it shows only in the gamepad look.",
			  path = "Settings > Bars > Controller", open = { "fluffy", "controller_page" },
			  client = "forever", card = true,
			  s = "A controller totem bar for WoW's gamepad look: d-pad cross, LB layer, a totem picker." },
			{ h = "Running out", icon = "Interface\\Icons\\Spell_Fire_FlameTounge",
			  b = "Show your shield and imbues only when they are running out. Turn them red, pulse, glow, drain the frame or a bar under them, and turn the time red. A gold look when a cooldown is almost ready. A red X until you put your imbue or shield back (5 seconds at most), and red while one is missing. The totem bar's Expiring Style gains Turns red.",
			  path = "Settings > Bars > Cooldown Bar", open = { "fluffy", "cdbar_page" },
			  card = true,
			  s = "Running out: show shields and imbues only while they run out, red, pulse or glow, and a red X until you put them back." },
			{ h = "Right-Click Casts Your Other Shield", icon = "Interface\\Icons\\Ability_Shaman_WaterShield",
			  b = "Optional: a right-click on the cooldown bar's shield button casts your other shield (Lightning or Water). Off to start.",
			  path = "Settings > Bars > Cooldown Bar > the shield item > Clicks", open = { "fluffy", "cdbar_page" } },
			{ h = "Next Shock", icon = "Interface\\Icons\\Spell_Fire_FlameShock",
			  b = "In Flame Shock's right-click menu on the Target Tracker: while your Flame Shock is on your target, its icon shows Earth Shock or Frost Shock instead, and Flame Shock again in its last seconds, on your target and on every nameplate.",
			  path = "Settings > Alerts & Reminders > Target Tracker", open = { "fluffy", "targettracker_section" } },
			{ h = "Ready Reminders: Fade Instead of Hide", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "In each icon's right-click menu, under Only In Combat: out of a fight the icon stays on screen, faded, so you can still see what's ready.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" } },
			{ h = "Your buff on its Ready Reminder", icon = "Interface\\Icons\\Spell_Holy_SealOfMight",
			  b = "Right-click a Stormstrike, Shamanistic Rage, Elemental Mastery or Nature's Swiftness icon: show the buff it gives you in the icon's corner, as its own icon, or as an edge. On WoW: Forever this is Improved Stormstrike; on TBC Anniversary it is Stormpower and friends. In a grid the buff goes In Its Own Spot.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" } },
			{ h = "Your key on Reactive Totems alerts", icon = "Interface\\Icons\\Spell_Nature_DiseaseCleansingTotem",
			  b = "Show Spell Keybind: the alert shows the key you bound to that totem, and a line when no key is bound.",
			  path = "Settings > Alerts & Reminders > Reactive Totems", open = { "fluffy", "reactivetotems_section" } },
			{ h = "Check After Resurrection", icon = "Interface\\Icons\\Spell_Nature_Reincarnation",
			  b = "Once you're alive again, the Ready Check list shows what to put back.",
			  path = "Settings > Group Tools > Ready Check", open = { "fluffy", "readycheck_section" } },
			{ h = "Party Strip", icon = "Interface\\Icons\\Spell_Nature_Windfury",
			  b = "A small strip you can move, one marker per party member, for the totems you pick in its Totems row. One line per totem, or Break Up Totem List for a strip per totem. It grows and shrinks with your party and works even with no totem down.",
			  path = "Settings > Group Tools > Party Buff Tracker > Party Strip", open = { "fluffy", "partystrip_section" },
			  card = true,
			  s = "Party Strip: one marker per party member for the totems you pick." },
			{ h = "Minimap ring colors", icon = "Interface\\Icons\\INV_Misc_Gem_Variety_01",
			  b = "Use My Own Ring Colors gives each element's range ring on the minimap a color you pick; off, the rings keep their element colors (or a theme's palette). Your colors travel with saved themes.",
			  path = "Settings > Totem Range Tracker > Minimap Markers", open = { "fluffy", "sprange_section" } },
			{ h = "Show a Tracked Totem's Icon", icon = "Interface\\Icons\\Spell_Nature_SkinofEarth",
			  b = "Always (as before), Not While It's Missing, or Only While I'm in Range. The overlay shrinks to the icons it shows.",
			  path = "Settings > Totem Range Tracker > Look", open = { "fluffy", "sprange_section" } },
		},
		changes = {
			"After updating, fully close and restart the game once: 3.0.8 adds new files (the settings pages, the Old Settings Look, Put Your Usual Totem Back, the controller bar), and a /reload alone does not load them.",
			"The cooldown bar's shield flyout: the shield you pick now works in fights too.",
			"Compact style with Show Keybinds on Buttons on: Your Shield Line shows your shield's key.",
			{ t = "Ready Check: anything the game hides from addons right now shows under a gray COULD NOT CHECK instead of being left out. An open list checks again when the game stops hiding it.", client = "forever" },
			{ t = "A shield you cast before your last death no longer counts while buffs are hidden.", client = "forever" },
			"Tooltips show the highest rank you know instead of rank 1.",
			"Settings menus refuse changes in a fight and say so, instead of failing quietly.",
		},
		fixes = {
			"WoW: Forever: Flametongue Totem no longer sits gray (out of range) on the totem bar however close you stand. There it is a buff on everyone in range, not a weapon enchant, and the bar read it the enchant way. After Totemic Projection the range look follows the spot the totems moved to.",
			{ t = "Ready Check: with the sweep switched off, the any-time totem item warnings stay quiet too. Before, Warn When a Totem Item Is Missing kept warning with the module off.", client = "forever" },
			"The switch beside Party Buff Tracker in the sidebar now turns the whole module off: the dots, the counters, Coverage and the Party Strip. Before, the Party Strip and Coverage stayed on screen.",
			"Totem Plates: the pulse timer on your own totem's plate ran from the moment the plate appeared, so it drifted from the bar's. It now runs from the totem's real drop time.",
			"Drop All's icon moves on only when that step's own totem is cast (any rank), never for another totem.",
			"Flyout clicks follow Swap Left and Right Click across profile switches, and hover flyouts keep their assign macro when swapped.",
			"The TotemTimers style's flyout hid the wrong totem.",
			"The main totem button's tooltip shows the spell again.",
			"Settings window: dragging the scroll bar no longer lags on long pages, a slider value past the ends stops at the track's end instead of running over the number box, and a dragged icon row shows its new order right away.",
			"Expiring Alerts show the totem's real icon.",
			"Drop All shows the totem it really drops next.",
			{ t = "Right-click cycling backward reaches the last totem.", client = "anniversary" },
			"Macros: the full message when a macro is made or updated.",
			"ES Tracker settings carry over from older versions.",
			"Totem Plates: a note on what WoW needs to show totem plates, with a button that turns Friendly Players and Friendly Minions on.",
			"Raid Cooldowns: the caller button's sweep clears properly.",
			"Coverage: the right icon in each cell.",
			{ t = "Target Tracker: an error on the Themes page.", client = "anniversary" },
			"Themes: a theme saved before an update puts the update's new settings back to their defaults, My Ring Colors survive a saved theme and a theme code, and Reactive Totems' glow is an effect, so themes leave it alone.",
			"Reset This Page on the Totem Bar page clears the Drop All icon too, and the icon picker's Okay waits for a fight to end.",
			{ t = "Wording that promised too much is now honest.", client = "forever" },
			"Reactive Totems: the old Click to Cast Totem switch that did nothing is hidden.",
		},
		also = "Next Shock on the Target Tracker, Fade Instead of Hide and your buff on Ready Reminders, your key on Reactive Totems alerts, Check After Resurrection, minimap ring colors, a key for Compact's shield line, and Right-Click Casts Your Other Shield",
		thanks = "Thanks to sopaaaaaa, Somatics, Alabamec, Rakii, z0mb and p0nts for the reports and ideas in this release.",
	},
	{
		v = "3.0.6.3",
		date = "2026-10-07",
		headline = "Pick an icon for Drop All, and its icon stays in step",
		new = {
			{ h = "Drop All Icon", icon = 136024,
			  b = "Pick any icon for the Drop All button instead of the icon of the totem it drops next: right-click the Drop All button on the Totem Bar page and choose Icon. It stays put, with Call of the Elements too. Next Totem puts the usual icon back.",
			  path = "Settings > Totem Bar > right-click the Drop All button > Icon", open = { "buttons", "auto_button" },
			  card = true,
			  s = "Pick any icon for the Drop All button, and it stays put." },
		},
		fixes = {
			"Drop All button (the one-totem-per-click version): a fast double-click, or a click that cast nothing, moved the button's icon on anyway, so from then on it showed one totem and dropped the next. The icon now asks the game where the button's sequence stands, so it moves only when a totem cast goes through, and forgets its place exactly when the button does: 15 seconds after the last press, at the end of a fight, or on death.",
			"Support Code with Deadly Boss Mods installed (WoW: Forever): pressing Support Code failed with \"Division by zero\" when DBM was loaded. DBM brings a newer copy of a shared library (LibSerialize) that WoW: Forever can't run, and the game uses whichever copy is newest. ShamanPower now ships the library's latest version, which has the fix, so the code builds with DBM on.",
			"My Assignments Follow Blizzard's Totem Bar (WoW: Forever): it did nothing unless Call of the Elements Follows My Assignments was on too (both are on the Buttons > Mini Totem Bar page). Each now works on its own: with only the first on, a totem you pick on Blizzard's bar still becomes your assignment, and when you log in your assignments take what is on the bar; with only the second on, Blizzard's bar still follows your assignments.",
		},
	},
	{
		v = "3.0.6.2",
		date = "2026-10-07",
		headline = "Your Fire totem no longer turns to Empty on its own",
		new = {},
		fixes = {
			"WoW: Forever: your Fire totem (or Water or Air) could turn to Empty on its own after a /reload or a loading screen, and the totem you put back on Blizzard's totem bar was wiped again the next time ShamanPower loaded. ShamanPower read Blizzard's totem bar before the game had finished loading it, took the empty slots for your choice, and then wrote that Empty back over the bar. Now only a totem you change on Blizzard's bar yourself counts, a totem on Blizzard's bar fills an Empty element instead of being wiped when ShamanPower loads, and a totem you pick on Blizzard's bar during a fight is kept when the fight ends.",
			"Support Code: on WoW: Forever, pressing Support Code could fail with \"could not build the support code\" when your settings held something the code can't carry. The code now always builds: anything it can't carry is left out, and the code says what was left out, so I can still see your setup.",
		},
	},
	{
		v = "3.0.6.1",
		date = "2026-10-06",
		headline = "The totem bar stays off, Compact's shield line in fights, and party dots",
		new = {},
		fixes = {
			"With Enable Totem Bar off, or Use in Party / Use when Solo off, the totem buttons came back after a fight or when you picked a totem on Blizzard's totem bar. They stay hidden now, and Use in Party / Use when Solo take effect right away.",
			"Dynamic Mode with Hide Out of Combat: no more loose totem buttons on screen after every fight.",
			"WoW: Forever, Compact style: Your Shield Line and the Earth Shield line keep showing your charges in fights instead of going dark (\"Not active\"). With Hide Out of Combat, your shield line comes and goes with the bar.",
			"Hide Out of Combat: a bar hidden since you logged in could show up in your first fight as plain icons. It now shows in your style.",
			"WoW: Forever: the Grays Out and Fills Back In sweeps on the cooldown bar and the shield button no longer show a stretched copy of the icon with hard edges in fights.",
			"Party Buff Tracker: a party member far away (in another zone, or out of sight) no longer lights your party dots or the Coverage list. On WoW: Forever the dots also only light for an element you have a totem down for.",
			"Keybind Mode shows Compact's shield line with the rest of the bar.",
		},
	},
	{
		v = "3.0.6",
		date = "2026-10-04",
		headline = "Target Tracker, every game language and a smarter cooldown bar",
		new = {
			{ h = "Target Tracker", icon = "Interface\\Icons\\Spell_Fire_FlameShock",
			  b = "Your Flame Shock, Frost Shock and Stormstrike on your target, where you want them: a spot you place, your target's nameplate, or under the target frame. Warn When It's Missing grays a shock out when it isn't on your target. Show On Every Enemy's Nameplate puts your shocks on every mob. The Purge reminder lights up when your target has a Magic buff you can remove. Rules switch any part on or off in a place or against a boss. It starts off: turn it on with the switch beside it.",
			  path = "Settings > Alerts & Reminders > Target Tracker", open = { "fluffy", "targettracker_section" },
			  card = true,
			  s = "Your shocks and Purge on your target, its nameplate or a spot you place." },
			{ h = "Every game language", icon = "Interface\\Icons\\INV_Misc_Map_01",
			  b = "Shields, totems, imbues, alerts and reminders now work in German, French, Spanish, Russian, Portuguese, Italian, Chinese and Korean. ShamanPower finds your spells by their ID, never their English name.",
			  card = true,
			  s = "Shields, totems, imbues and alerts work in every game language." },
			{ h = "Ready Reminders, made simple", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "Every setting is in each icon's right-click menu, with sliders right in the menu and Copy To All Icons. New: Out of Range (red tint, gray or dim), Ready Flash (a big flash when a spell is ready, which you can move), and a sound per icon.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" },
			  card = true,
			  s = "Every setting in each icon's right-click menu, plus Out of Range and Ready Flash." },
			{ h = "The cooldown bar follows your totem bar style", icon = "Interface\\Icons\\Spell_Fire_FlameTounge",
			  b = "The shield and imbue buttons work the way your totems do in your style: Normal, TotemTimers, Single, Dynamic or Grid. If you want a different one, turn on Do Not Mirror Totem Bar Style and pick it.",
			  path = "Settings > Bars > Cooldown Bar > Display", open = { "fluffy", "cooldown_display_section" },
			  card = true,
			  s = "Shield and imbue buttons work like your totems, or pick their own style." },
			{ h = "A new look for the settings", icon = "Interface\\Icons\\INV_Misc_Gem_Variety_01",
			  b = "Pages lit by each group's element, the logo and new fonts. Preview and Reset This Page on every page. A module's page grays out with a Turn On button while the module is off. Menus and tooltips got the same look. The settings window can also drop in and fly away, and Unlock UI's boxes rise into place: that's off to start, so turn on UI Animations at the top of the settings sidebar if you'd like it.",
			  path = "Settings", open = { "settings", "settings_show" },
			  card = true,
			  s = "Element-lit pages, Preview and Reset This Page everywhere, and a new menu look." },
			{ h = "Tremor Reminder at boss pulls", icon = "Interface\\Icons\\Spell_Nature_TremorTotem",
			  b = "In dungeons and raids it comes up the moment a fight with a fearing boss starts, even without targeting the boss.",
			  path = "Settings > Alerts & Reminders > Tremor Reminder", open = { "fluffy", "tremorreminder_section" } },
			{ h = "Sound When Your Shield Drops", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "Now in fights too.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_section" } },
		},
		changes = {
			"Flyouts and the totem bar only show totems you've learned.",
			"Party dots and Totem Coverage count only your own totems.",
			"Every vertical sweep has a Sweep Direction.",
			"Cooldown bar flyouts never repeat what's on the button, and a right-click assign stays put.",
			"With two weapons, a right-click imbue pick is your off hand's, and the button's right-click applies it again.",
			{ t = "Raid Cooldowns' sound plays at its own volume, not your Dialog volume.", client = "forever" },
			{ t = "Trainer Reminder matches your trainer exactly.", client = "forever" },
			{ t = "Keybinds for Call of the Elements, Ancestors and Spirits.", client = "forever" },
			"Expiring Alerts stay quiet after logging in and after loading screens.",
			"Tooltips in ShamanPower's windows show at the mouse.",
			"The setup tour (/spsetup) has a Target Tracker step, right after Ready Reminders.",
		},
		fixes = {
			"Shields, totems and alerts didn't work in German and other non-English clients.",
			"In Spanish, and for a few totems in Portuguese, French, Russian and Chinese, the bar couldn't tell which totem was down: no timer, duration bar, pulse, range or party dot for it.",
			{ t = "The Earth Shield macro showed a question mark on non-English clients.", client = "anniversary" },
			"Tauren saw Nature Resistance Totem from level 1, and Flametongue and Windfury Totem showed as soon as the weapon imbue was learned.",
			{ t = "The shield-gone sound didn't play in fights.", client = "forever" },
			{ t = "The totem bar's vertical cooldown sweeps drew a squashed second icon, hard edges and all, over the real one.", client = "forever" },
			"The What's New card could run off the bottom of the screen.",
			"The imbue flyout showed the imbue already on the button.",
		},
		also = "Tremor Reminder at boss pulls, Sound When Your Shield Drops in fights, and UI Animations (off to start, at the top of the settings sidebar)",
	},
	{
		v = "3.0.5.1",
		date = "2026-10-02",
		headline = "Fixes for the October 1 WoW: Forever patch",
		new = {},
		changes = {
			"Get Help: Copy Support Code also says whether ShamanPower and each of its modules loaded (and why not), when your settings were last saved, BugSack's ShamanPower errors and anything the game blocked, so #help can answer without asking you to type commands.",
		},
		fixes = {
			"WoW: Forever: after the October 1 patch, ShamanPower thought it was running on TBC Anniversary. Forever's own options (Right-Click to Destroy Totems, Raid Resistance and more) went missing, Totem Twisting options showed up, and settings could look reset. Everything is back.",
			"WoW: Forever: no more Lua errors in combat from the shield check and the Earth Shield Tracker.",
			"WoW: Forever: Reactive Totems' Tremor Totem alert shows only while you're feared, charmed or asleep, not for roots, Frost Nova or stuns. It's for you only now: the game doesn't tell addons what kind of crowd control is on someone else.",
		},
	},
	{
		v = "3.0.5",
		date = "2026-09-30",
		headline = "Your own themes, a support code and a better Unlock UI",
		new = {
			{ h = "Your Themes", icon = "Interface\\Icons\\INV_Misc_Gem_Variety_01",
			  b = "Save your look under a name, pick it on any character, and share it with a code. Standard, ShamanPower and ShamanPower Minimal are now fixed presets: anything you change becomes your Custom look until you save it or discard it. Your look from 3.0.4 is kept as a theme called \"My Look\".",
			  path = "Settings > General > Themes", open = { "settings", "settings_themes" },
			  card = true, look = true,
			  s = "Save your look as a theme, use it on any character, share it with a code." },
			{ h = "Get Help: Copy Support Code", icon = "Interface\\Icons\\INV_Letter_15",
			  b = "Something not working? Copy your Support Code and paste it in #help on the ShamanPower Discord, and I can see what's going on without asking you to run commands. Nothing personal goes in it. Also: /sp support.",
			  path = "Settings > General > Main", open = { "settings", "settings_show" },
			  card = true,
			  s = "One code to paste in #help on the Discord when something's wrong." },
			{ h = "Unlock UI: snap, nudge and resize", icon = "Interface\\Icons\\INV_Misc_Wrench_01",
			  b = "Boxes snap to each other and to the screen center as you drag them, with gold lines showing what they lined up with. Click one and nudge it with the arrow keys, change its size with the mouse wheel and its opacity with Ctrl + wheel, or right-click it for its settings page.",
			  path = "Settings > General > Main > Unlock UI", open = { "settings", "settings_show" },
			  card = true,
			  s = "Snapping, arrow-key nudging, and the mouse wheel for size and opacity." },
			{ h = "Ready Reminders: Only While on Cooldown, and Grid", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "Show an icon only while its spell recharges, and put the reminders in one Grid block you move as a whole: it fills in the order they appear, with no gaps.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" },
			  card = true,
			  s = "Icons only while on cooldown, and a Grid placement with no gaps." },
			{ h = "Keybinds tab", icon = "Interface\\Icons\\INV_Misc_Key_03",
			  b = "Keybind Mode, Show Keybinds on Buttons and the new Keybind Shown in one place: show your action bar key first (as before), ShamanPower's own key first, or ShamanPower's key only. Keys you set in Keybind Mode now show on the buttons.",
			  path = "Settings > General > Keybinds", open = { "settings", "settings_keybinds" },
			  card = true,
			  s = "Choose which key the buttons show; Keybind Mode keys now show on them." },
		},
		changes = {
			"ShamanPower uses about half the CPU it did out of combat, and less in fights.",
			{ t = "Buff changes that can't affect your shield or Earth Shield no longer make ShamanPower read your buffs again, which matters most in raids.", client = "anniversary" },
			"Cooldown Bar > Display: Duration Text Location and Size sit next to Show Cooldown Text.",
			{ t = "Ready Reminders' Gray Out The Icon also grays the icon under a sweep.", client = "forever" },
			"The settings' live preview pauses while Unlock UI is on.",
		},
		fixes = {
			{ t = "With Questie installed, the cooldown bar's shield never lit up: Questie brings its own version of a game function ShamanPower used. ShamanPower now uses its own.", client = "forever" },
			"Unlock UI's grid centers boxes properly.",
			"The cooldown bar's Radial sweep no longer shows the game's own countdown when Show Cooldown Text is off.",
			{ t = "The cooldown bar's shield shows right after a reload in combat.", client = "forever" },
			{ t = "Mana Tide's level 48 and 58 ranks end the cooldown bar alert.", client = "forever" },
			"Reset All Colors keeps every color it clears on the Custom card.",
			"Party dots no longer leave a gap outside a group with Dot Position Below, Above, Left or Right.",
			{ t = "Flametongue Totem is no longer tracked (its dots were always red).", client = "anniversary" },
			"Ready Reminders' Reset Position resets only the placement you're using.",
			"Unlock UI: Shield Charges gets one box per real frame, with the right names.",
			"Raid Cooldowns: the Mana Tide call buttons no longer pile up in memory as the group syncs.",
		},
		also = "about half the CPU out of combat, and on WoW: Forever the cooldown bar's shield now works with Questie installed",
		thanks = "Thanks to Miska for the new Ready Reminders modes, and to ShamanForever's author for the ideas behind Unlock UI's snapping and nudging.",
	},
	{
		v = "3.0.4.1",
		date = "2026-09-29",
		headline = "A fix for a Lua error about the totem bar's size",
		new = {},
		changes = {},
		fixes = {
			"No more Lua error when ShamanPower puts the totem bar or the cooldown bar on its default spot and the totem bar's button size is missing from your settings.",
			"Importing a setup (a shared code, a backup or Srumar's Layout) fills in any setting the code leaves out straight away.",
		},
	},
	{
		v = "3.0.4",
		date = "2026-09-29",
		headline = "Shapes, gradients and class colors",
		new = {
			{ h = "Shapes, gradients and class colors", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "Round, rounded or flat icons for each bar, with borders that follow the shape. Gradients on the bars and outlines, round glows and dots, frame edges, and five class color sets for the party dots with a gem finish. Nothing changes until you pick something.",
			  path = "Settings > General > Themes", open = { "settings", "settings_themes" },
			  card = true, look = true,
			  s = "Round, rounded or flat icons, gradients, round glows and dots, and five class color sets." },
			{ h = "Shield Charges: orbs", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "Show each shield's charges as orbs: Glowing, Flat, the shield's icon, Storm, Bubble and more. Each shield has its own color and gradient, an optional animation, and the orbs can stand up beside you.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_section" },
			  card = true,
			  s = "Each shield's charges as orbs, with their own color, gradient and animation." },
			{ h = "Combined Shocks", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "One Ready Reminder for Earth, Flame and Frost Shock: it cycles through the three, or shows them split in thirds. It follows the shared shock cooldown.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" },
			  card = true,
			  s = "One Ready Reminder for all three shocks." },
			{ h = "Right-click for the flyout", icon = "Interface\\Icons\\Spell_Nature_GroundingTotem",
			  b = "Open a totem's flyout with a right-click, and Shift+Right-Click pulls just that totem back. Swap Left and Right Click turns it around.",
			  path = "Settings > Bars > Totem Bar > Clicks", open = { "settings", "settings_totemClicks" },
			  card = true,
			  s = "Right-click opens the flyout; Shift+Right-Click pulls that totem back." },
			{ h = "Windfury on WoW: Forever", icon = "Interface\\Icons\\Spell_Nature_Windfury",
			  b = "Windfury Totem is a party buff on Forever, so the party dots, Totem Coverage and the Totem Range Tracker follow it like Strength of Earth.",
			  client = "forever", card = true,
			  s = "Party dots, Totem Coverage and the Totem Range Tracker follow Windfury Totem." },
		},
		changes = {
			"Patch Notes in the settings: every version's notes, newest first.",
			"Reset Everything on the Themes tab puts every look back to default; the Custom card keeps your whole look to bring back.",
			"Every color from the other settings pages also sits in its section on the Themes tab, and the Themes tab is in the settings search.",
			"ShamanPower's own page in WoW's Options window opens the settings, the setup tour, What's New or the Discord link.",
			"Duration Bar Background: turn off the dark track behind the duration bars.",
			"Border Size for the Element-Colored Borders, and borders on the cooldown bar's shield and imbue flyouts.",
			"Shield Charges have their own bar texture, gradient and colors; Bar Texture and Bar Gradient never change them.",
			"Ready Reminders: Icon Shape and Hide Border.",
			"Only Show Pulse Flash for Specific Totems: the pulse flash gets its own totem list.",
			{ t = "Windfury-only mode is gone on WoW: Forever, where Windfury Totem is a party buff.", client = "forever" },
		},
		fixes = {
			{ t = "Totem of Wrath is a Fire totem again, with its timer and duration bar.", client = "anniversary" },
			{ t = "A cooldown shortened or reset mid-fight now counts down its real time on the bars.", client = "forever" },
			"Totem Range Tracker: Show Overlay switches off even while the settings preview is open.",
			"Hovering any part of a settings button shows its tooltip, not only its border.",
			"Volume sliders move in 1% steps.",
			"The Duration Bars preview follows Only Show Pulse Bars for Specific Totems.",
		},
		also = "a Duration Bar Background switch, Reset Everything on the Themes tab, your Custom look now keeps every setting, search on the Themes tab, ShamanPower's own page in WoW's Options window, and on Anniversary Totem of Wrath shows its timer and duration bar again",
	},
	{
		v = "3.0.3",
		date = "2026-09-28",
		headline = "Themes, Effects and new Shield Charges looks",
		new = {
			{ h = "Themes: the ShamanPower look", icon = "Interface\\Icons\\Spell_Nature_GuardianWard",
			  b = "Pick a look for all of ShamanPower at once: Standard (your look today), ShamanPower or ShamanPower Minimal. Change any part on its own, down to a single dot color; Standard always puts your own settings back.",
			  path = "Settings > General > Themes", open = { "settings", "settings_themes" },
			  card = true,
			  s = "Pick a look for all of ShamanPower at once; Standard always puts yours back." },
			{ h = "Effects", icon = "Interface\\Icons\\Spell_Nature_Lightning",
			  b = "A short animation on a button when something happens to it: a totem destroyed or run out, a cooldown ready, an imbue or shield gone. Sixteen styles and three Effects Looks, all off until you turn them on.",
			  path = "Settings > Bars > Totem Bar > Effects", open = { "fluffy", "totembar_effects_section" } },
			{ h = "Single Totem style", icon = "Interface\\Icons\\Spell_Nature_TremorTotem",
			  b = "The button shows the totem that is down, but a click always drops your assigned one, and the button goes back to it once the dropped totem is gone. Drop a Tremor or Grounding in PvP without losing your set.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" } },
			{ h = "Shield Charges: new looks", icon = "Interface\\Icons\\Ability_Shaman_WaterShield",
			  b = "Show the shield's icon with the count on it, and a charge bar with one segment per charge: below, above, or standing up beside the display. The cooldown bar's shield button can show the charge bar too.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_section" } },
			{ h = "More control over duration and pulse bars", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "Opacity for the duration bars, pulse bars and pulse flash, Pulse Bar and Pulse Flash Colors, and pulse bars only for the totems you pick.",
			  path = "Settings > Bars > Totem Bar > Duration Bars", open = { "fluffy", "totembar_duration_section" } },
			{ h = "Hide Blizzard's Totem Timers", icon = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
			  b = "Hides the small totem icons and timers WoW shows under your player frame. They come back when you turn it off.",
			  path = "Settings > General > Main", open = { "settings", "settings_show" } },
			{ h = "ShamanPower's own color picker", icon = "Interface\\Icons\\Spell_Nature_WispSplode",
			  b = "Every color option opens it: a color square, a hex box, the ShamanPower, Blizzard and Classic palettes and WoW's own colors. Cancel puts the old color back." },
			{ h = "Only Show Who's Missing", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "Party dots only for the members without the totem's buff, so no dots means everyone is covered.",
			  path = "Settings > Group Tools > Party Buff Tracker > Dots & Counters", open = { "fluffy", "partybuff_section" } },
			{ h = "Totem Coverage: more ways to show it", icon = "Interface\\Icons\\Spell_Nature_ManaRegenTotem",
			  b = "Dots instead of names, only who's missing, the totem's time left, and a plain totem icon.",
			  path = "Settings > Group Tools > Party Buff Tracker > Coverage", open = { "fluffy", "coverage_section" },
			  client = "forever" },
		},
		changes = {
			"Reset All Colors on the Themes tab puts every color in ShamanPower back to how it came.",
			"Brand-new installs get a Pick your look step in the setup tour.",
			"Cooldown bar: Show Shield Charge Bar, and Show Shield Charge Count to turn the corner number off.",
			"Ready Reminders: Chain Lightning is in the list, and Only In Combat sits next to Show.",
			"Stoneclaw Totem gets the pulse bar and glow, timed to its taunt.",
			"Totem Range Tracker: show the overlay in a group with a shaman, in any group, or always.",
			"Lighter in combat: Shield Charges, Reactive Totems and the combat code do far less work.",
			"The Totem Bar Style dropdown replaces the old on/off switch for each style.",
			"Buttons in the settings, the setup tour and ShamanPower's pop-ups have depth, and the close X turns red when you point at it.",
		},
		fixes = {
			{ t = "Totem Expired alerts show in combat.", client = "forever" },
			{ t = "No false \"Lightning Shield FADED!\" at the start of a fight.", client = "forever" },
			{ t = "No more errors from hovering the bars and party frames in combat.", client = "forever" },
			{ t = "Tremor Totem's pulse timer follows its real 4-second pulse.", client = "forever" },
			{ t = "Ready Check no longer warns about a Fire Totem after a Fire Nova with no Fire totem down.", client = "forever" },
			{ t = "Earth Shield fade alerts keep working when the raid moves your Earth Shield target.", client = "anniversary" },
			{ t = "A totem picked mid-fight for an element with nothing assigned casts from its button.", client = "anniversary" },
			"A totem picked from a flyout mid-fight shows everywhere on the bar right away and stays picked.",
			"Expiring Alerts do far less work in raids.",
			"TotemTimers Style with Empty assigned shows the running totem.",
			"The bar frames grow to wrap the flyout arrows in combat.",
			"Totem flyouts sort around the new totems right after you switch loadouts.",
			"TotemTimers Style flyouts redraw straight away after you drop a totem.",
			"Cooldown bar flyouts offer a new imbue or shield as soon as you learn it.",
			"Dragging a slider in the settings no longer slows the game, and percentage sliders move in 1% steps.",
		},
	},
	{
		v = "3.0.2",
		date = "2026-09-26",
		headline = "Cooldown bar shield key fix on WoW: Forever",
		new = {},
		changes = {},
		fixes = {
			{ t = "Your action-bar key for Lightning or Water Shield casts again with Blizzard-Style Flyout Arrows and Swap Left and Right Click on, and imbue keys go to the main hand.", client = "forever" },
		},
	},
	{
		v = "3.0.1",
		date = "2026-09-26",
		headline = "Hover flyouts on WoW: Forever",
		new = {
			{ h = "Hover flyouts on WoW: Forever", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "The totem, cooldown bar and loadout flyouts open when you hover the button, in combat too, just like on Anniversary.",
			  client = "forever" },
			{ h = "Blizzard-Style Flyout Arrows", icon = "Interface\\Icons\\Spell_Nature_SlowingTotem",
			  b = "Prefer the click-to-open arrows of Blizzard's totem bar? Turn this on, then reload. Off by default.",
			  path = "Settings > Bars > Appearance > Flyouts", open = { "fluffy", "flyout_appearance" },
			  client = "forever" },
			{ h = "Empty Totem in Flyouts", icon = "Interface\\Icons\\Spell_Nature_DiseaseCleansingTotem",
			  b = "Pick Empty, in or out of combat, to leave an element with no totem so Call of the Elements skips it.",
			  path = "Settings > Bars > Totem Bar > Style", open = { "settings", "settings_totemMode" },
			  client = "forever" },
		},
		changes = {
			{ t = "The setup tour and the settings preview show Blizzard's flyout arrows on the Blizzard's Totem Bar style.", client = "forever" },
		},
		fixes = {
			"Assigning a totem from a flyout in combat now really assigns it: the button casts the new totem straight away.",
			"No more gap between the loadout flyout's buttons.",
			"Importing a setup code only ever writes ShamanPower's own settings.",
		},
	},
	{
		v = "3.0.0",
		date = "2026-09-25",
		headline = "ShamanPower on WoW: Forever",
		new = {
			{ h = "ShamanPower runs on WoW: Forever", icon = "Interface\\Icons\\ClassIcon_Shaman",
			  b = "One download for both games. On Forever the totem timers, party dots and alerts keep working in combat, and totems that game does not have are hidden everywhere. Forever characters start with the setup tour.",
			  card = true,
			  s = "One download for both games; the timers, party dots and alerts keep working in combat there." },
			{ h = "Blizzard's Totem Bar, powered by ShamanPower", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "Keep the game's own totem bar and get ShamanPower's countdowns, duration bars, pulse timers and party dots on its buttons. Blizzard's three totem sets stay in step with your assignments and loadouts.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" },
			  client = "forever", card = true, try = "blizzard",
			  when = function() return ShamanPower.TotemBarStyle and ShamanPower:TotemBarStyle("blizzard") ~= nil end,
			  s = "The game's own totem bar with ShamanPower's countdowns, bars and dots on it." },
			{ h = "Totem Coverage: who is missing your buff", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "The reverse of Totem Range: under each of your totems, the names of the party members who do NOT have its buff, in red or class color. It hides itself once everyone is covered, in combat too.",
			  path = "Settings > Group Tools > Party Buff Tracker > Coverage", open = { "fluffy", "coverage_section" },
			  client = "forever", card = true,
			  when = function() return ShamanPower.CoverageAvailable and ShamanPower:CoverageAvailable() end,
			  s = "The names of party members without your totem's buff, under each totem." },
			{ h = "Auto-Assign picks by who is in the group", icon = "Interface\\Icons\\Spell_Nature_StoneSkinTotem",
			  b = "Stoneskin for caster-only groups and Strength of Earth with melee; Mana Spring with mana users, Healing Stream otherwise; the Air totem by who benefits.",
			  card = true,
			  s = "Stoneskin or Strength of Earth, Mana Spring or Healing Stream, the Air totem by who benefits." },
			{ h = "Grid style", icon = "Interface\\Icons\\Spell_Fire_SearingTotem",
			  b = "Every totem of every element at once, in rows: click to drop, the assigned one highlighted, the timer on the dropped one. Split by Element makes each row its own movable frame.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" } },
			{ h = "Ready Reminders", icon = "Interface\\Icons\\Spell_Fire_FlameShock",
			  b = "Icons that light up when a spell comes off cooldown: shocks, Stormstrike, Nature's Swiftness, Mana Tide, Grounding and more. Show them only when ready, always, or dimmed with a countdown.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" } },
			{ h = "Fonts and bar textures", icon = "Interface\\Icons\\INV_Misc_Note_01",
			  b = "Pick the font, outline and bar texture for everything ShamanPower draws, or give timers, charges, alerts and names their own. Hover one to see it on your frames first.",
			  path = "Settings > General > Fonts & Textures", open = { "settings", "settings_fonts" } },
			{ h = "Live preview in the settings", icon = "Interface\\Icons\\INV_Misc_Gear_01",
			  b = "The arrow tab on the right shows the page's module with your settings, redrawn as you change them. Every window a module has opens from a button on its page." },
			{ h = "Totem markers on the minimap", icon = "Interface\\Icons\\INV_Misc_Map_01",
			  b = "A pin where each totem was dropped and a ring for its reach, turning with the minimap. Open world only.",
			  path = "Settings > Group Tools > Totem Range Tracker", open = { "fluffy", "sprange_section" },
			  client = "forever" },
			{ h = "Raid resistance requests", icon = "Interface\\Icons\\Spell_FireResistanceTotem_01",
			  b = "Resistance totems reach the whole raid on Forever. Ask for one and ShamanPower asks the shaman whose group loses least; they Accept or Pass.",
			  path = "Settings > Group Tools > Raid Resistance", open = { "buttons", "resist_section" },
			  client = "forever" },
			{ h = "Loadout Auto-Switch", icon = "Interface\\Icons\\Spell_Nature_RavenForm",
			  b = "Pick a loadout for raids, dungeons, battlegrounds and the open world, or add rules by zone, target or boss. It never switches in combat.",
			  path = "Settings > Bars > Loadouts > Auto-Switch", open = { "buttons", "loadoutrules_section" } },
			{ h = "Ready Check sweep", icon = "Interface\\Icons\\Spell_Holy_MindSooth",
			  b = "On a ready check ShamanPower lists what you are missing: shield, weapon imbue, totem items, assigned totems not down, low mana.",
			  path = "Settings > Group Tools > Ready Check", open = { "fluffy", "readycheck_section" } },
			{ h = "Cooldown Announce", icon = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
			  b = "Announce Mana Tide when you use it and before it is back, and answer \"tide\" in group chat with ready or the seconds left. All off by default.",
			  path = "Settings > Group Tools > Cooldown Announce", open = { "fluffy", "announce_section" } },
			{ h = "Keybind Mode", icon = "Interface\\Icons\\Ability_Parry",
			  b = "Every ShamanPower button that can take a key lights up with its key: hover one and press a key to bind it. /sp bind." },
			{ h = "Trainer Reminder", icon = "Interface\\Icons\\INV_Hammer_04",
			  b = "When you level up, the shaman spells and ranks now waiting at your trainer. Only you see it.",
			  path = "Settings > Alerts & Reminders > Trainer Reminder", open = { "fluffy", "trainer_section" },
			  client = "forever" },
		},
		changes = {
			"The settings are reorganized: General, Bars, Group Tools, Alerts & Reminders and Other, with Loadouts on its own page.",
			"Enable ShamanPower turns the whole addon off while every setting stays open to change.",
			"Unlock UI moves everything ShamanPower draws, each frame with its own Reset and an optional alignment grid.",
			"First login is a small choice: take the setup tour, or use Srumar's setup in one click.",
			"Each totem bar style keeps its own spot on screen.",
			"Minimap icon: right-click for a quick menu of styles, loadouts, Unlock UI, Keybind Mode and settings.",
			"Share My Setup: a short code of which features you use, to share in #setup-stats on the Discord.",
			"Mana Tint: totem and cooldown buttons turn blue while you cannot afford them.",
			{ t = "Totem twisting is not offered on Forever, where Windfury Totem no longer stacks with the other Air totems.", client = "forever" },
		},
		fixes = {
			"Built for 40-player raids: ShamanPower does far less work in big groups and when idle.",
			"Newly trained totems show in the flyouts without a reload.",
			"The cooldown bar's raid-call alert shows again, and a repeat call keeps it going.",
			"Pulse bars no longer stay hidden after Pulse Bar Position went to None and back.",
			"Applying Srumar's Layout never replaces your saved loadouts.",
			{ t = "Totem Destroyed alerts work in combat.", client = "forever" },
			{ t = "Names: you no longer appear twice in the assignments window, and raid calls addressed to you are recognized.", client = "forever" },
			{ t = "The loadout bar's flyout opens.", client = "forever" },
		},
		also = "totem markers on the minimap, your own font, a live preview in the settings, a reorganized settings window, Enable ShamanPower to turn it all off, a Grid style",
	},
	{
		v = "2.1.1",
		date = "2026-09-16",
		headline = "Reactive Totems fix for Tremor Totem",
		new = {},
		changes = {},
		fixes = {
			"Reactive Totems: Hide When Totem Active works for Tremor Totem, so the fear alert goes away while a Tremor Totem is down.",
		},
	},
	{
		v = "2.1.0",
		date = "2026-09-16",
		headline = "The Compact totem bar style",
		new = {
			{ h = "Compact style", icon = "Interface\\Icons\\Spell_Nature_ManaRegenTotem",
			  b = "No icons: each element is a colored line that drains as the totem runs down and refills with every pulse. Stacked or side by side, any length and thickness, with optional shield charge lines.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" } },
			{ h = "Only Show Learned Elements", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "A new shaman's bar grows with them: each element appears as its first totem is learned, and the bar stays centered. On by default.",
			  path = "Settings > Bars > Totem Bar > Items", open = { "fluffy", "totembar_items_section" } },
		},
		changes = {},
		fixes = {
			"Expiring Alerts: Earth and Fire totem alerts were swapped. If you turned one off to work around it, check both toggles again.",
			"ShamanPower is back under Options > AddOns.",
		},
	},
	{
		v = "2.0.7",
		date = "2026-09-16",
		headline = "Earth Shield tracking that survives a reload",
		new = {},
		changes = {},
		fixes = {
			{ t = "Earth Shield tracking survives a /reload and casts on someone you have not targeted, and an Earth Shield already out is picked up at login.", client = "anniversary" },
		},
	},
	{
		v = "2.0.6",
		date = "2026-09-16",
		headline = "Pop-out trackers stay put",
		new = {
			{ h = "Lock All Pop-Out Trackers", icon = "Interface\\Icons\\INV_Shield_06",
			  b = "While it is on, no pop-out tracker can be dragged. Turn it off to rearrange them.",
			  path = "Settings > Other > Pop-Out Trackers" },
		},
		changes = {},
		fixes = {
			"Pop-out trackers no longer move a little on every /reload.",
		},
	},
	{
		v = "2.0.5",
		date = "2026-09-16",
		headline = "Earth Shield fade alert fixed",
		new = {},
		changes = {},
		fixes = {
			{ t = "Expiring Alerts: the Earth Shield fade alert fires, on your target or on yourself, in party and raid.", client = "anniversary" },
			"Settings labels are no longer cut short with \"...\" when there is room for them.",
		},
	},
	{
		v = "2.0.4",
		date = "2026-09-01",
		headline = "Earth Shield Flyout Filter and smarter flyouts",
		new = {
			{ h = "Earth Shield Flyout Filter", icon = "Interface\\Icons\\Spell_Nature_SkinofEarth",
			  b = "Show only the players you would actually shield: pick roles, classes or both. Your assigned target always shows.",
			  path = "Settings > Bars > Totem Bar > Flyouts", open = { "fluffy", "totemflyouts_section" },
			  client = "anniversary" },
			{ h = "Flyouts that open away from the screen edge", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "With the flyout direction on Auto, the totem bar and Earth Shield flyouts open downward near the top of the screen and upward near the bottom." },
			{ h = "Dropped Totem Indicator Position", icon = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
			  b = "Choose where the icon of a dropped, non-assigned totem pops out: Auto, Above, Below, Left or Right." },
			{ h = "Talent totems without a reload", icon = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
			  b = "Mana Tide and Totem of Wrath show up in the flyouts, and leave them, when you respec." },
			{ h = "What's New", icon = "Interface\\Icons\\INV_Misc_Note_01",
			  b = "A small card after an update with the big changes. Open it again any time with /spwhatsnew." },
		},
		changes = {},
		fixes = {
			{ t = "The Earth Shield flyout closes when the mouse leaves and after you pick someone, and opens on the right side on vertical bars.", client = "anniversary" },
			{ t = "The Earth Shield button no longer flickers while your shield is on someone other than your assigned target.", client = "anniversary" },
			"Respeccing out of Restoration clears a Mana Tide assignment, as it does for Totem of Wrath.",
			"Totems turned off in the flyout settings stay out of the flyout after a right-click assignment.",
		},
	},
	{
		v = "2.0.3",
		date = "2026-08-28",
		headline = "No more stutter from quiet alert sounds",
		new = {},
		changes = {},
		fixes = {
			"An alert sound played below 100% volume no longer makes the game stutter.",
			"Overlapping alerts no longer leave your Dialog volume changed.",
		},
	},
	{
		v = "2.0.2",
		date = "2026-08-28",
		headline = "Totem Assignments click fix",
		new = {},
		changes = {},
		fixes = {
			"Totem Assignments: left-clicking past the last totem wraps back to none, as right-click already did.",
		},
	},
	{
		v = "2.0.1",
		date = "2026-08-28",
		headline = "Your existing setup is safe",
		new = {
			{ h = "Automatic backup of your setup", icon = "Interface\\Icons\\INV_Shield_06",
			  b = "Before a spec pick or a built-in layout replaces your setup, ShamanPower saves the whole thing first and tells you where to get it back. The last three are kept.",
			  path = "Settings > General > Profiles", open = { "profiles" } },
			{ h = "Restore My Previous Setup", icon = "Interface\\Icons\\Spell_Nature_Reincarnation",
			  b = "Brings a backup back as a new profile, so nothing is overwritten during the restore either.",
			  path = "Settings > General > Profiles", open = { "profiles" } },
		},
		changes = {
			"Running the setup again never changes your settings; the spec's starting defaults only apply to a fresh install.",
			"Preview Srumar's Layout on the Profiles page before applying it.",
		},
		fixes = {},
	},
	{
		v = "2.0.0",
		date = "2026-08-28",
		headline = "The setup tour and the new settings window",
		new = {
			{ h = "A new settings window", icon = "Interface\\Icons\\INV_Misc_Gear_01",
			  b = "Sidebar pages with tabs, search across every setting, and scrollbars everywhere. /sp, the minimap icon and Options > AddOns all open it." },
			{ h = "The setup tour", icon = "Interface\\Icons\\ClassIcon_Shaman",
			  b = "Pick your spec, then every feature is explained and shown working live, with its real options next to it. Open it again any time with /sp setup." },
			{ h = "A short setup for other classes", icon = "Interface\\Icons\\INV_Misc_QuestionMark",
			  b = "Non-shamans get a short tour of what runs for them: Totem Range, Raid Cooldowns, Totem Plates and the Windfury Companion." },
			{ h = "Srumar's Layout and profile sharing", icon = "Interface\\Icons\\INV_BannerPVP_02",
			  b = "A complete ready-made setup you can preview before applying it. Profiles can be exported as a code and imported, no reload.",
			  path = "Settings > General > Profiles", open = { "profiles" } },
			{ h = "Windfury Companion", icon = "Interface\\Icons\\Spell_Nature_Windfury",
			  b = "A small WeakAura for your melee: with it, your Air slot counts who has Windfury and whether they are in range.",
			  client = "anniversary" },
			{ h = "Cooldown styles", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "Radial sweep, a vertical gray-out or a vertical fill-back for totem cooldowns and the cooldown bar, with the time shown if you like.",
			  path = "Settings > Bars > Totem Bar > Duration Bars", open = { "fluffy", "totembar_duration_section" } },
			{ h = "Party dot placement", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "Dot Position (corners, a row or a column), Dot Outline and Dot Size for the party buff dots.",
			  path = "Settings > Group Tools > Party Buff Tracker > Dots & Counters", open = { "fluffy", "partybuff_section" } },
			{ h = "Drums of Battle callers", icon = "Interface\\Icons\\INV_Misc_Drum_02",
			  b = "One caller and one drummer per raid group: pressing the caller shows every assigned drummer a USE DRUMS NOW alert.",
			  path = "Settings > Group Tools > Raid Cooldowns", open = { "fluffy", "raid_cd_section" },
			  client = "anniversary" },
		},
		changes = {
			"Frame positions survive resolution and UI scale changes, and scaling a frame keeps it in place.",
			"Pop-out trackers, the Raid Cooldowns window, the Totem Range overlay and the totem assignment window have the new look.",
			"Unlock Bar on the Totem Bar and Cooldown Bar pages: drag the bar from anywhere, no Alt key.",
			"Test Sound buttons next to every sound picker.",
			"The cooldown bar always floats free of the totem bar.",
			"Only the TBC Anniversary client: the Vanilla and Wrath versions are gone.",
		},
		fixes = {
			"Nature's Swiftness, Shamanistic Rage and Bloodlust buttons show when they are active.",
			"Repeated raid cooldown calls from non-shamans are no longer dropped after the first press.",
		},
	},
}

-- (the Tester's automatic checks read the notes through this; nothing else does)
if ShamanPower then ShamanPower.PATCH_NOTES = ns.PATCH_NOTES end
