local _, ns = ...
-- Patch Notes (Settings > Patch Notes) and the What's New card read these; newest first.
-- Curated: what a player notices. Each version: new = full items (icon, title, a few
-- words, the settings page it lives on), changes / fixes = one line each.
-- client = "forever" / "anniversary" marks what only one game has; card = true puts an
-- item on the What's New card (s = its one-line short row for players updating from far
-- back); look = true is the card's NEW box; also = the card's Also line; thanks = a
-- line at the bottom of the version's Patch Notes (never on the card).
ns.PATCH_NOTES = {
	{
		v = "3.0.6",
		date = "2026-10-04",
		headline = "Target Tracker, every game language and a smarter cooldown bar",
		new = {
			{ h = "Target Tracker", icon = "Interface\\Icons\\Spell_Fire_FlameShock",
			  b = "Your Flame Shock, Frost Shock and Stormstrike on your target, where you want them: a spot you place, your target's nameplate, or under the target frame. Warn When It's Missing grays a shock out when it isn't on your target. Show On Every Enemy's Nameplate puts your shocks on every mob. The Purge reminder lights up when your target has a Magic buff you can remove. Rules switch any part on or off in a place or against a boss. It starts off: turn it on with the switch beside it.",
			  path = "Settings > Alerts & Reminders > Target Tracker", open = { "fluffy", "targettracker_section" },
			  card = true,
			  s = "Your shocks and Purge on your target, its nameplate or a spot you place." },
			{ h = "Every game language", icon = "Interface\\Icons\\INV_Misc_Map_01",
			  b = "Shields, totems, imbues, alerts and reminders now work in German, French, Spanish, Russian, Portuguese, Italian, Chinese and Korean. ShamanPower finds your spells by their ID, never their English name.",
			  card = true,
			  s = "Shields, totems, imbues and alerts work in every game language." },
			{ h = "Ready Reminders, made simple", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "Every setting is in each icon's right-click menu, with sliders right in the menu and Copy To All Icons. New: Out of Range (red tint, gray or dim), Ready Flash (a big flash when a spell is ready, which you can move), and a sound per icon.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" },
			  card = true,
			  s = "Every setting in each icon's right-click menu, plus Out of Range and Ready Flash." },
			{ h = "The cooldown bar follows your totem bar style", icon = "Interface\\Icons\\Spell_Fire_FlameTounge",
			  b = "The shield and imbue buttons work the way your totems do in your style: Normal, TotemTimers, Single, Dynamic or Grid. If you want a different one, turn on Do Not Mirror Totem Bar Style and pick it.",
			  path = "Settings > Bars > Cooldown Bar > Display", open = { "fluffy", "cooldown_display_section" },
			  card = true,
			  s = "Shield and imbue buttons work like your totems, or pick their own style." },
			{ h = "A new look for the settings", icon = "Interface\\Icons\\INV_Misc_Gem_Variety_01",
			  b = "Pages lit by each group's element, the logo and new fonts. Preview and Reset This Page on every page. A module's page grays out with a Turn On button while the module is off. Menus and tooltips got the same look. The settings window can also drop in and fly away, and Unlock UI's boxes rise into place: that's off to start, so turn on UI Animations at the top of the settings sidebar if you'd like it.",
			  path = "Settings", open = { "settings", "settings_show" },
			  card = true,
			  s = "Element-lit pages, Preview and Reset This Page everywhere, and a new menu look." },
			{ h = "Tremor Reminder at boss pulls", icon = "Interface\\Icons\\Spell_Nature_TremorTotem",
			  b = "In dungeons and raids it comes up the moment a fight with a fearing boss starts, even without targeting the boss.",
			  path = "Settings > Alerts & Reminders > Tremor Reminder", open = { "fluffy", "tremorreminder_section" } },
			{ h = "Sound When Your Shield Drops", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "Now in fights too.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_section" } },
		},
		changes = {
			"Flyouts and the totem bar only show totems you've learned.",
			"Party dots and Totem Coverage count only your own totems.",
			"Every vertical sweep has a Sweep Direction.",
			"Cooldown bar flyouts never repeat what's on the button, and a right-click assign stays put.",
			"With two weapons, a right-click imbue pick is your off hand's, and the button's right-click applies it again.",
			{ t = "Raid Cooldowns' sound plays at its own volume, not your Dialog volume.", client = "forever" },
			{ t = "Trainer Reminder matches your trainer exactly.", client = "forever" },
			{ t = "Keybinds for Call of the Elements, Ancestors and Spirits.", client = "forever" },
			"Expiring Alerts stay quiet after logging in and after loading screens.",
			"Tooltips in ShamanPower's windows show at the mouse.",
			"The setup tour (/spsetup) has a Target Tracker step, right after Ready Reminders.",
		},
		fixes = {
			"Shields, totems and alerts didn't work in German and other non-English clients.",
			"In Spanish, and for a few totems in Portuguese, French, Russian and Chinese, the bar couldn't tell which totem was down: no timer, duration bar, pulse, range or party dot for it.",
			{ t = "The Earth Shield macro showed a question mark on non-English clients.", client = "anniversary" },
			"Tauren saw Nature Resistance Totem from level 1, and Flametongue and Windfury Totem showed as soon as the weapon imbue was learned.",
			{ t = "The shield-gone sound didn't play in fights.", client = "forever" },
			{ t = "The totem bar's vertical cooldown sweeps drew a squashed second icon, hard edges and all, over the real one.", client = "forever" },
			"The What's New card could run off the bottom of the screen.",
			"The imbue flyout showed the imbue already on the button.",
		},
		also = "Tremor Reminder at boss pulls, Sound When Your Shield Drops in fights, and UI Animations (off to start, at the top of the settings sidebar)",
	},
	{
		v = "3.0.5.1",
		date = "2026-10-02",
		headline = "Fixes for the October 1 WoW: Forever patch",
		new = {},
		changes = {
			"Get Help: Copy Support Code also says whether ShamanPower and each of its modules loaded (and why not), when your settings were last saved, BugSack's ShamanPower errors and anything the game blocked, so #help can answer without asking you to type commands.",
		},
		fixes = {
			"WoW: Forever: after the October 1 patch, ShamanPower thought it was running on TBC Anniversary. Forever's own options (Right-Click to Destroy Totems, Raid Resistance and more) went missing, Totem Twisting options showed up, and settings could look reset. Everything is back.",
			"WoW: Forever: no more Lua errors in combat from the shield check and the Earth Shield Tracker.",
			"WoW: Forever: Reactive Totems' Tremor Totem alert shows only while you're feared, charmed or asleep, not for roots, Frost Nova or stuns. It's for you only now: the game doesn't tell addons what kind of crowd control is on someone else.",
		},
	},
	{
		v = "3.0.5",
		date = "2026-09-30",
		headline = "Your own themes, a support code and a better Unlock UI",
		new = {
			{ h = "Your Themes", icon = "Interface\\Icons\\INV_Misc_Gem_Variety_01",
			  b = "Save your look under a name, pick it on any character, and share it with a code. Standard, ShamanPower and ShamanPower Minimal are now fixed presets: anything you change becomes your Custom look until you save it or discard it. Your look from 3.0.4 is kept as a theme called \"My Look\".",
			  path = "Settings > General > Themes", open = { "settings", "settings_themes" },
			  card = true, look = true,
			  s = "Save your look as a theme, use it on any character, share it with a code." },
			{ h = "Get Help: Copy Support Code", icon = "Interface\\Icons\\INV_Letter_15",
			  b = "Something not working? Copy your Support Code and paste it in #help on the ShamanPower Discord, and I can see what's going on without asking you to run commands. Nothing personal goes in it. Also: /sp support.",
			  path = "Settings > General > Main", open = { "settings", "settings_show" },
			  card = true,
			  s = "One code to paste in #help on the Discord when something's wrong." },
			{ h = "Unlock UI: snap, nudge and resize", icon = "Interface\\Icons\\INV_Misc_Wrench_01",
			  b = "Boxes snap to each other and to the screen center as you drag them, with gold lines showing what they lined up with. Click one and nudge it with the arrow keys, change its size with the mouse wheel and its opacity with Ctrl + wheel, or right-click it for its settings page.",
			  path = "Settings > General > Main > Unlock UI", open = { "settings", "settings_show" },
			  card = true,
			  s = "Snapping, arrow-key nudging, and the mouse wheel for size and opacity." },
			{ h = "Ready Reminders: Only While on Cooldown, and Grid", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "Show an icon only while its spell recharges, and put the reminders in one Grid block you move as a whole: it fills in the order they appear, with no gaps.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" },
			  card = true,
			  s = "Icons only while on cooldown, and a Grid placement with no gaps." },
			{ h = "Keybinds tab", icon = "Interface\\Icons\\INV_Misc_Key_03",
			  b = "Keybind Mode, Show Keybinds on Buttons and the new Keybind Shown in one place: show your action bar key first (as before), ShamanPower's own key first, or ShamanPower's key only. Keys you set in Keybind Mode now show on the buttons.",
			  path = "Settings > General > Keybinds", open = { "settings", "settings_keybinds" },
			  card = true,
			  s = "Choose which key the buttons show; Keybind Mode keys now show on them." },
		},
		changes = {
			"ShamanPower uses about half the CPU it did out of combat, and less in fights.",
			{ t = "Buff changes that can't affect your shield or Earth Shield no longer make ShamanPower read your buffs again, which matters most in raids.", client = "anniversary" },
			"Cooldown Bar > Display: Duration Text Location and Size sit next to Show Cooldown Text.",
			{ t = "Ready Reminders' Gray Out The Icon also grays the icon under a sweep.", client = "forever" },
			"The settings' live preview pauses while Unlock UI is on.",
		},
		fixes = {
			{ t = "With Questie installed, the cooldown bar's shield never lit up: Questie brings its own version of a game function ShamanPower used. ShamanPower now uses its own.", client = "forever" },
			"Unlock UI's grid centers boxes properly.",
			"The cooldown bar's Radial sweep no longer shows the game's own countdown when Show Cooldown Text is off.",
			{ t = "The cooldown bar's shield shows right after a reload in combat.", client = "forever" },
			{ t = "Mana Tide's level 48 and 58 ranks end the cooldown bar alert.", client = "forever" },
			"Reset All Colors keeps every color it clears on the Custom card.",
			"Party dots no longer leave a gap outside a group with Dot Position Below, Above, Left or Right.",
			{ t = "Flametongue Totem is no longer tracked (its dots were always red).", client = "anniversary" },
			"Ready Reminders' Reset Position resets only the placement you're using.",
			"Unlock UI: Shield Charges gets one box per real frame, with the right names.",
			"Raid Cooldowns: the Mana Tide call buttons no longer pile up in memory as the group syncs.",
		},
		also = "about half the CPU out of combat, and on WoW: Forever the cooldown bar's shield now works with Questie installed",
		thanks = "Thanks to Miska for the new Ready Reminders modes, and to ShamanForever's author for the ideas behind Unlock UI's snapping and nudging.",
	},
	{
		v = "3.0.4.1",
		date = "2026-09-29",
		headline = "A fix for a Lua error about the totem bar's size",
		new = {},
		changes = {},
		fixes = {
			"No more Lua error when ShamanPower puts the totem bar or the cooldown bar on its default spot and the totem bar's button size is missing from your settings.",
			"Importing a setup (a shared code, a backup or Srumar's Layout) fills in any setting the code leaves out straight away.",
		},
	},
	{
		v = "3.0.4",
		date = "2026-09-29",
		headline = "Shapes, gradients and class colors",
		new = {
			{ h = "Shapes, gradients and class colors", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "Round, rounded or flat icons for each bar, with borders that follow the shape. Gradients on the bars and outlines, round glows and dots, frame edges, and five class color sets for the party dots with a gem finish. Nothing changes until you pick something.",
			  path = "Settings > General > Themes", open = { "settings", "settings_themes" },
			  card = true, look = true,
			  s = "Round, rounded or flat icons, gradients, round glows and dots, and five class color sets." },
			{ h = "Shield Charges: orbs", icon = "Interface\\Icons\\Spell_Nature_LightningShield",
			  b = "Show each shield's charges as orbs: Glowing, Flat, the shield's icon, Storm, Bubble and more. Each shield has its own color and gradient, an optional animation, and the orbs can stand up beside you.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_section" },
			  card = true,
			  s = "Each shield's charges as orbs, with their own color, gradient and animation." },
			{ h = "Combined Shocks", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "One Ready Reminder for Earth, Flame and Frost Shock: it cycles through the three, or shows them split in thirds. It follows the shared shock cooldown.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" },
			  card = true,
			  s = "One Ready Reminder for all three shocks." },
			{ h = "Right-click for the flyout", icon = "Interface\\Icons\\Spell_Nature_GroundingTotem",
			  b = "Open a totem's flyout with a right-click, and Shift+Right-Click pulls just that totem back. Swap Left and Right Click turns it around.",
			  path = "Settings > Bars > Totem Bar > Clicks", open = { "settings", "settings_totemClicks" },
			  card = true,
			  s = "Right-click opens the flyout; Shift+Right-Click pulls that totem back." },
			{ h = "Windfury on WoW: Forever", icon = "Interface\\Icons\\Spell_Nature_Windfury",
			  b = "Windfury Totem is a party buff on Forever, so the party dots, Totem Coverage and the Totem Range Tracker follow it like Strength of Earth.",
			  client = "forever", card = true,
			  s = "Party dots, Totem Coverage and the Totem Range Tracker follow Windfury Totem." },
		},
		changes = {
			"Patch Notes in the settings: every version's notes, newest first.",
			"Reset Everything on the Themes tab puts every look back to default; the Custom card keeps your whole look to bring back.",
			"Every color from the other settings pages also sits in its section on the Themes tab, and the Themes tab is in the settings search.",
			"ShamanPower's own page in WoW's Options window opens the settings, the setup tour, What's New or the Discord link.",
			"Duration Bar Background: turn off the dark track behind the duration bars.",
			"Border Size for the Element-Colored Borders, and borders on the cooldown bar's shield and imbue flyouts.",
			"Shield Charges have their own bar texture, gradient and colors; Bar Texture and Bar Gradient never change them.",
			"Ready Reminders: Icon Shape and Hide Border.",
			"Only Show Pulse Flash for Specific Totems: the pulse flash gets its own totem list.",
			{ t = "Windfury-only mode is gone on WoW: Forever, where Windfury Totem is a party buff.", client = "forever" },
		},
		fixes = {
			{ t = "Totem of Wrath is a Fire totem again, with its timer and duration bar.", client = "anniversary" },
			{ t = "A cooldown shortened or reset mid-fight now counts down its real time on the bars.", client = "forever" },
			"Totem Range Tracker: Show Overlay switches off even while the settings preview is open.",
			"Hovering any part of a settings button shows its tooltip, not only its border.",
			"Volume sliders move in 1% steps.",
			"The Duration Bars preview follows Only Show Pulse Bars for Specific Totems.",
		},
		also = "a Duration Bar Background switch, Reset Everything on the Themes tab, your Custom look now keeps every setting, search on the Themes tab, ShamanPower's own page in WoW's Options window, and on Anniversary Totem of Wrath shows its timer and duration bar again",
	},
	{
		v = "3.0.3",
		date = "2026-09-28",
		headline = "Themes, Effects and new Shield Charges looks",
		new = {
			{ h = "Themes: the ShamanPower look", icon = "Interface\\Icons\\Spell_Nature_GuardianWard",
			  b = "Pick a look for all of ShamanPower at once: Standard (your look today), ShamanPower or ShamanPower Minimal. Change any part on its own, down to a single dot color; Standard always puts your own settings back.",
			  path = "Settings > General > Themes", open = { "settings", "settings_themes" },
			  card = true,
			  s = "Pick a look for all of ShamanPower at once; Standard always puts yours back." },
			{ h = "Effects", icon = "Interface\\Icons\\Spell_Nature_Lightning",
			  b = "A short animation on a button when something happens to it: a totem destroyed or run out, a cooldown ready, an imbue or shield gone. Sixteen styles and three Effects Looks, all off until you turn them on.",
			  path = "Settings > Bars > Totem Bar > Effects", open = { "fluffy", "totembar_effects_section" } },
			{ h = "Single Totem style", icon = "Interface\\Icons\\Spell_Nature_TremorTotem",
			  b = "The button shows the totem that is down, but a click always drops your assigned one, and the button goes back to it once the dropped totem is gone. Drop a Tremor or Grounding in PvP without losing your set.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" } },
			{ h = "Shield Charges: new looks", icon = "Interface\\Icons\\Ability_Shaman_WaterShield",
			  b = "Show the shield's icon with the count on it, and a charge bar with one segment per charge: below, above, or standing up beside the display. The cooldown bar's shield button can show the charge bar too.",
			  path = "Settings > Alerts & Reminders > Shield Charges", open = { "fluffy", "shieldcharges_section" } },
			{ h = "More control over duration and pulse bars", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "Opacity for the duration bars, pulse bars and pulse flash, Pulse Bar and Pulse Flash Colors, and pulse bars only for the totems you pick.",
			  path = "Settings > Bars > Totem Bar > Duration Bars", open = { "fluffy", "totembar_duration_section" } },
			{ h = "Hide Blizzard's Totem Timers", icon = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
			  b = "Hides the small totem icons and timers WoW shows under your player frame. They come back when you turn it off.",
			  path = "Settings > General > Main", open = { "settings", "settings_show" } },
			{ h = "ShamanPower's own color picker", icon = "Interface\\Icons\\Spell_Nature_WispSplode",
			  b = "Every color option opens it: a color square, a hex box, the ShamanPower, Blizzard and Classic palettes and WoW's own colors. Cancel puts the old color back." },
			{ h = "Only Show Who's Missing", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "Party dots only for the members without the totem's buff, so no dots means everyone is covered.",
			  path = "Settings > Group Tools > Party Buff Tracker > Dots & Counters", open = { "fluffy", "partybuff_section" } },
			{ h = "Totem Coverage: more ways to show it", icon = "Interface\\Icons\\Spell_Nature_ManaRegenTotem",
			  b = "Dots instead of names, only who's missing, the totem's time left, and a plain totem icon.",
			  path = "Settings > Group Tools > Party Buff Tracker > Coverage", open = { "fluffy", "coverage_section" },
			  client = "forever" },
		},
		changes = {
			"Reset All Colors on the Themes tab puts every color in ShamanPower back to how it came.",
			"Brand-new installs get a Pick your look step in the setup tour.",
			"Cooldown bar: Show Shield Charge Bar, and Show Shield Charge Count to turn the corner number off.",
			"Ready Reminders: Chain Lightning is in the list, and Only In Combat sits next to Show.",
			"Stoneclaw Totem gets the pulse bar and glow, timed to its taunt.",
			"Totem Range Tracker: show the overlay in a group with a shaman, in any group, or always.",
			"Lighter in combat: Shield Charges, Reactive Totems and the combat code do far less work.",
			"The Totem Bar Style dropdown replaces the old on/off switch for each style.",
			"Buttons in the settings, the setup tour and ShamanPower's pop-ups have depth, and the close X turns red when you point at it.",
		},
		fixes = {
			{ t = "Totem Expired alerts show in combat.", client = "forever" },
			{ t = "No false \"Lightning Shield FADED!\" at the start of a fight.", client = "forever" },
			{ t = "No more errors from hovering the bars and party frames in combat.", client = "forever" },
			{ t = "Tremor Totem's pulse timer follows its real 4-second pulse.", client = "forever" },
			{ t = "Ready Check no longer warns about a Fire Totem after a Fire Nova with no Fire totem down.", client = "forever" },
			{ t = "Earth Shield fade alerts keep working when the raid moves your Earth Shield target.", client = "anniversary" },
			{ t = "A totem picked mid-fight for an element with nothing assigned casts from its button.", client = "anniversary" },
			"A totem picked from a flyout mid-fight shows everywhere on the bar right away and stays picked.",
			"Expiring Alerts do far less work in raids.",
			"TotemTimers Style with Empty assigned shows the running totem.",
			"The bar frames grow to wrap the flyout arrows in combat.",
			"Totem flyouts sort around the new totems right after you switch loadouts.",
			"TotemTimers Style flyouts redraw straight away after you drop a totem.",
			"Cooldown bar flyouts offer a new imbue or shield as soon as you learn it.",
			"Dragging a slider in the settings no longer slows the game, and percentage sliders move in 1% steps.",
		},
	},
	{
		v = "3.0.2",
		date = "2026-09-26",
		headline = "Cooldown bar shield key fix on WoW: Forever",
		new = {},
		changes = {},
		fixes = {
			{ t = "Your action-bar key for Lightning or Water Shield casts again with Blizzard-Style Flyout Arrows and Swap Left and Right Click on, and imbue keys go to the main hand.", client = "forever" },
		},
	},
	{
		v = "3.0.1",
		date = "2026-09-26",
		headline = "Hover flyouts on WoW: Forever",
		new = {
			{ h = "Hover flyouts on WoW: Forever", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "The totem, cooldown bar and loadout flyouts open when you hover the button, in combat too, just like on Anniversary.",
			  client = "forever" },
			{ h = "Blizzard-Style Flyout Arrows", icon = "Interface\\Icons\\Spell_Nature_SlowingTotem",
			  b = "Prefer the click-to-open arrows of Blizzard's totem bar? Turn this on, then reload. Off by default.",
			  path = "Settings > Bars > Appearance > Flyouts", open = { "fluffy", "flyout_appearance" },
			  client = "forever" },
			{ h = "Empty Totem in Flyouts", icon = "Interface\\Icons\\Spell_Nature_DiseaseCleansingTotem",
			  b = "Pick Empty, in or out of combat, to leave an element with no totem so Call of the Elements skips it.",
			  path = "Settings > Bars > Totem Bar > Style", open = { "settings", "settings_totemMode" },
			  client = "forever" },
		},
		changes = {
			{ t = "The setup tour and the settings preview show Blizzard's flyout arrows on the Blizzard's Totem Bar style.", client = "forever" },
		},
		fixes = {
			"Assigning a totem from a flyout in combat now really assigns it: the button casts the new totem straight away.",
			"No more gap between the loadout flyout's buttons.",
			"Importing a setup code only ever writes ShamanPower's own settings.",
		},
	},
	{
		v = "3.0.0",
		date = "2026-09-25",
		headline = "ShamanPower on WoW: Forever",
		new = {
			{ h = "ShamanPower runs on WoW: Forever", icon = "Interface\\Icons\\ClassIcon_Shaman",
			  b = "One download for both games. On Forever the totem timers, party dots and alerts keep working in combat, and totems that game does not have are hidden everywhere. Forever characters start with the setup tour.",
			  card = true,
			  s = "One download for both games; the timers, party dots and alerts keep working in combat there." },
			{ h = "Blizzard's Totem Bar, powered by ShamanPower", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "Keep the game's own totem bar and get ShamanPower's countdowns, duration bars, pulse timers and party dots on its buttons. Blizzard's three totem sets stay in step with your assignments and loadouts.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" },
			  client = "forever", card = true, try = "blizzard",
			  when = function() return ShamanPower.TotemBarStyle and ShamanPower:TotemBarStyle("blizzard") ~= nil end,
			  s = "The game's own totem bar with ShamanPower's countdowns, bars and dots on it." },
			{ h = "Totem Coverage: who is missing your buff", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "The reverse of Totem Range: under each of your totems, the names of the party members who do NOT have its buff, in red or class color. It hides itself once everyone is covered, in combat too.",
			  path = "Settings > Group Tools > Party Buff Tracker > Coverage", open = { "fluffy", "coverage_section" },
			  client = "forever", card = true,
			  when = function() return ShamanPower.CoverageAvailable and ShamanPower:CoverageAvailable() end,
			  s = "The names of party members without your totem's buff, under each totem." },
			{ h = "Auto-Assign picks by who is in the group", icon = "Interface\\Icons\\Spell_Nature_StoneSkinTotem",
			  b = "Stoneskin for caster-only groups and Strength of Earth with melee; Mana Spring with mana users, Healing Stream otherwise; the Air totem by who benefits.",
			  card = true,
			  s = "Stoneskin or Strength of Earth, Mana Spring or Healing Stream, the Air totem by who benefits." },
			{ h = "Grid style", icon = "Interface\\Icons\\Spell_Fire_SearingTotem",
			  b = "Every totem of every element at once, in rows: click to drop, the assigned one highlighted, the timer on the dropped one. Split by Element makes each row its own movable frame.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" } },
			{ h = "Ready Reminders", icon = "Interface\\Icons\\Spell_Fire_FlameShock",
			  b = "Icons that light up when a spell comes off cooldown: shocks, Stormstrike, Nature's Swiftness, Mana Tide, Grounding and more. Show them only when ready, always, or dimmed with a countdown.",
			  path = "Settings > Alerts & Reminders > Ready Reminders", open = { "fluffy", "readyreminders_section" } },
			{ h = "Fonts and bar textures", icon = "Interface\\Icons\\INV_Misc_Note_01",
			  b = "Pick the font, outline and bar texture for everything ShamanPower draws, or give timers, charges, alerts and names their own. Hover one to see it on your frames first.",
			  path = "Settings > General > Fonts & Textures", open = { "settings", "settings_fonts" } },
			{ h = "Live preview in the settings", icon = "Interface\\Icons\\INV_Misc_Gear_01",
			  b = "The arrow tab on the right shows the page's module with your settings, redrawn as you change them. Every window a module has opens from a button on its page." },
			{ h = "Totem markers on the minimap", icon = "Interface\\Icons\\INV_Misc_Map_01",
			  b = "A pin where each totem was dropped and a ring for its reach, turning with the minimap. Open world only.",
			  path = "Settings > Group Tools > Totem Range Tracker", open = { "fluffy", "sprange_section" },
			  client = "forever" },
			{ h = "Raid resistance requests", icon = "Interface\\Icons\\Spell_FireResistanceTotem_01",
			  b = "Resistance totems reach the whole raid on Forever. Ask for one and ShamanPower asks the shaman whose group loses least; they Accept or Pass.",
			  path = "Settings > Group Tools > Raid Resistance", open = { "buttons", "resist_section" },
			  client = "forever" },
			{ h = "Loadout Auto-Switch", icon = "Interface\\Icons\\Spell_Nature_RavenForm",
			  b = "Pick a loadout for raids, dungeons, battlegrounds and the open world, or add rules by zone, target or boss. It never switches in combat.",
			  path = "Settings > Bars > Loadouts > Auto-Switch", open = { "buttons", "loadoutrules_section" } },
			{ h = "Ready Check sweep", icon = "Interface\\Icons\\Spell_Holy_MindSooth",
			  b = "On a ready check ShamanPower lists what you are missing: shield, weapon imbue, totem items, assigned totems not down, low mana.",
			  path = "Settings > Group Tools > Ready Check", open = { "fluffy", "readycheck_section" } },
			{ h = "Cooldown Announce", icon = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
			  b = "Announce Mana Tide when you use it and before it is back, and answer \"tide\" in group chat with ready or the seconds left. All off by default.",
			  path = "Settings > Group Tools > Cooldown Announce", open = { "fluffy", "announce_section" } },
			{ h = "Keybind Mode", icon = "Interface\\Icons\\Ability_Parry",
			  b = "Every ShamanPower button that can take a key lights up with its key: hover one and press a key to bind it. /sp bind." },
			{ h = "Trainer Reminder", icon = "Interface\\Icons\\INV_Hammer_04",
			  b = "When you level up, the shaman spells and ranks now waiting at your trainer. Only you see it.",
			  path = "Settings > Alerts & Reminders > Trainer Reminder", open = { "fluffy", "trainer_section" },
			  client = "forever" },
		},
		changes = {
			"The settings are reorganized: General, Bars, Group Tools, Alerts & Reminders and Other, with Loadouts on its own page.",
			"Enable ShamanPower turns the whole addon off while every setting stays open to change.",
			"Unlock UI moves everything ShamanPower draws, each frame with its own Reset and an optional alignment grid.",
			"First login is a small choice: take the setup tour, or use Srumar's setup in one click.",
			"Each totem bar style keeps its own spot on screen.",
			"Minimap icon: right-click for a quick menu of styles, loadouts, Unlock UI, Keybind Mode and settings.",
			"Share My Setup: a short code of which features you use, to share in #setup-stats on the Discord.",
			"Mana Tint: totem and cooldown buttons turn blue while you cannot afford them.",
			{ t = "Totem twisting is not offered on Forever, where Windfury Totem no longer stacks with the other Air totems.", client = "forever" },
		},
		fixes = {
			"Built for 40-player raids: ShamanPower does far less work in big groups and when idle.",
			"Newly trained totems show in the flyouts without a reload.",
			"The cooldown bar's raid-call alert shows again, and a repeat call keeps it going.",
			"Pulse bars no longer stay hidden after Pulse Bar Position went to None and back.",
			"Applying Srumar's Layout never replaces your saved loadouts.",
			{ t = "Totem Destroyed alerts work in combat.", client = "forever" },
			{ t = "Names: you no longer appear twice in the assignments window, and raid calls addressed to you are recognized.", client = "forever" },
			{ t = "The loadout bar's flyout opens.", client = "forever" },
		},
		also = "totem markers on the minimap, your own font, a live preview in the settings, a reorganized settings window, Enable ShamanPower to turn it all off, a Grid style",
	},
	{
		v = "2.1.1",
		date = "2026-09-16",
		headline = "Reactive Totems fix for Tremor Totem",
		new = {},
		changes = {},
		fixes = {
			"Reactive Totems: Hide When Totem Active works for Tremor Totem, so the fear alert goes away while a Tremor Totem is down.",
		},
	},
	{
		v = "2.1.0",
		date = "2026-09-16",
		headline = "The Compact totem bar style",
		new = {
			{ h = "Compact style", icon = "Interface\\Icons\\Spell_Nature_ManaRegenTotem",
			  b = "No icons: each element is a colored line that drains as the totem runs down and refills with every pulse. Stacked or side by side, any length and thickness, with optional shield charge lines.",
			  path = "Settings > General > Main > Totem Bar Style", open = { "settings", "settings_show" } },
			{ h = "Only Show Learned Elements", icon = "Interface\\Icons\\Spell_Nature_EarthBindTotem",
			  b = "A new shaman's bar grows with them: each element appears as its first totem is learned, and the bar stays centered. On by default.",
			  path = "Settings > Bars > Totem Bar > Items", open = { "fluffy", "totembar_items_section" } },
		},
		changes = {},
		fixes = {
			"Expiring Alerts: Earth and Fire totem alerts were swapped. If you turned one off to work around it, check both toggles again.",
			"ShamanPower is back under Options > AddOns.",
		},
	},
	{
		v = "2.0.7",
		date = "2026-09-16",
		headline = "Earth Shield tracking that survives a reload",
		new = {},
		changes = {},
		fixes = {
			{ t = "Earth Shield tracking survives a /reload and casts on someone you have not targeted, and an Earth Shield already out is picked up at login.", client = "anniversary" },
		},
	},
	{
		v = "2.0.6",
		date = "2026-09-16",
		headline = "Pop-out trackers stay put",
		new = {
			{ h = "Lock All Pop-Out Trackers", icon = "Interface\\Icons\\INV_Shield_06",
			  b = "While it is on, no pop-out tracker can be dragged. Turn it off to rearrange them.",
			  path = "Settings > Other > Pop-Out Trackers" },
		},
		changes = {},
		fixes = {
			"Pop-out trackers no longer move a little on every /reload.",
		},
	},
	{
		v = "2.0.5",
		date = "2026-09-16",
		headline = "Earth Shield fade alert fixed",
		new = {},
		changes = {},
		fixes = {
			{ t = "Expiring Alerts: the Earth Shield fade alert fires, on your target or on yourself, in party and raid.", client = "anniversary" },
			"Settings labels are no longer cut short with \"...\" when there is room for them.",
		},
	},
	{
		v = "2.0.4",
		date = "2026-09-01",
		headline = "Earth Shield Flyout Filter and smarter flyouts",
		new = {
			{ h = "Earth Shield Flyout Filter", icon = "Interface\\Icons\\Spell_Nature_SkinofEarth",
			  b = "Show only the players you would actually shield: pick roles, classes or both. Your assigned target always shows.",
			  path = "Settings > Bars > Totem Bar > Flyouts", open = { "fluffy", "totemflyouts_section" },
			  client = "anniversary" },
			{ h = "Flyouts that open away from the screen edge", icon = "Interface\\Icons\\Spell_Nature_InvisibilityTotem",
			  b = "With the flyout direction on Auto, the totem bar and Earth Shield flyouts open downward near the top of the screen and upward near the bottom." },
			{ h = "Dropped Totem Indicator Position", icon = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
			  b = "Choose where the icon of a dropped, non-assigned totem pops out: Auto, Above, Below, Left or Right." },
			{ h = "Talent totems without a reload", icon = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
			  b = "Mana Tide and Totem of Wrath show up in the flyouts, and leave them, when you respec." },
			{ h = "What's New", icon = "Interface\\Icons\\INV_Misc_Note_01",
			  b = "A small card after an update with the big changes. Open it again any time with /spwhatsnew." },
		},
		changes = {},
		fixes = {
			{ t = "The Earth Shield flyout closes when the mouse leaves and after you pick someone, and opens on the right side on vertical bars.", client = "anniversary" },
			{ t = "The Earth Shield button no longer flickers while your shield is on someone other than your assigned target.", client = "anniversary" },
			"Respeccing out of Restoration clears a Mana Tide assignment, as it does for Totem of Wrath.",
			"Totems turned off in the flyout settings stay out of the flyout after a right-click assignment.",
		},
	},
	{
		v = "2.0.3",
		date = "2026-08-28",
		headline = "No more stutter from quiet alert sounds",
		new = {},
		changes = {},
		fixes = {
			"An alert sound played below 100% volume no longer makes the game stutter.",
			"Overlapping alerts no longer leave your Dialog volume changed.",
		},
	},
	{
		v = "2.0.2",
		date = "2026-08-28",
		headline = "Totem Assignments click fix",
		new = {},
		changes = {},
		fixes = {
			"Totem Assignments: left-clicking past the last totem wraps back to none, as right-click already did.",
		},
	},
	{
		v = "2.0.1",
		date = "2026-08-28",
		headline = "Your existing setup is safe",
		new = {
			{ h = "Automatic backup of your setup", icon = "Interface\\Icons\\INV_Shield_06",
			  b = "Before a spec pick or a built-in layout replaces your setup, ShamanPower saves the whole thing first and tells you where to get it back. The last three are kept.",
			  path = "Settings > General > Profiles", open = { "profiles" } },
			{ h = "Restore My Previous Setup", icon = "Interface\\Icons\\Spell_Nature_Reincarnation",
			  b = "Brings a backup back as a new profile, so nothing is overwritten during the restore either.",
			  path = "Settings > General > Profiles", open = { "profiles" } },
		},
		changes = {
			"Running the setup again never changes your settings; the spec's starting defaults only apply to a fresh install.",
			"Preview Srumar's Layout on the Profiles page before applying it.",
		},
		fixes = {},
	},
	{
		v = "2.0.0",
		date = "2026-08-28",
		headline = "The setup tour and the new settings window",
		new = {
			{ h = "A new settings window", icon = "Interface\\Icons\\INV_Misc_Gear_01",
			  b = "Sidebar pages with tabs, search across every setting, and scrollbars everywhere. /sp, the minimap icon and Options > AddOns all open it." },
			{ h = "The setup tour", icon = "Interface\\Icons\\ClassIcon_Shaman",
			  b = "Pick your spec, then every feature is explained and shown working live, with its real options next to it. Open it again any time with /sp setup." },
			{ h = "A short setup for other classes", icon = "Interface\\Icons\\INV_Misc_QuestionMark",
			  b = "Non-shamans get a short tour of what runs for them: Totem Range, Raid Cooldowns, Totem Plates and the Windfury Companion." },
			{ h = "Srumar's Layout and profile sharing", icon = "Interface\\Icons\\INV_BannerPVP_02",
			  b = "A complete ready-made setup you can preview before applying it. Profiles can be exported as a code and imported, no reload.",
			  path = "Settings > General > Profiles", open = { "profiles" } },
			{ h = "Windfury Companion", icon = "Interface\\Icons\\Spell_Nature_Windfury",
			  b = "A small WeakAura for your melee: with it, your Air slot counts who has Windfury and whether they are in range.",
			  client = "anniversary" },
			{ h = "Cooldown styles", icon = "Interface\\Icons\\Spell_Nature_EarthShock",
			  b = "Radial sweep, a vertical gray-out or a vertical fill-back for totem cooldowns and the cooldown bar, with the time shown if you like.",
			  path = "Settings > Bars > Totem Bar > Duration Bars", open = { "fluffy", "totembar_duration_section" } },
			{ h = "Party dot placement", icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
			  b = "Dot Position (corners, a row or a column), Dot Outline and Dot Size for the party buff dots.",
			  path = "Settings > Group Tools > Party Buff Tracker > Dots & Counters", open = { "fluffy", "partybuff_section" } },
			{ h = "Drums of Battle callers", icon = "Interface\\Icons\\INV_Misc_Drum_02",
			  b = "One caller and one drummer per raid group: pressing the caller shows every assigned drummer a USE DRUMS NOW alert.",
			  path = "Settings > Group Tools > Raid Cooldowns", open = { "fluffy", "raid_cd_section" },
			  client = "anniversary" },
		},
		changes = {
			"Frame positions survive resolution and UI scale changes, and scaling a frame keeps it in place.",
			"Pop-out trackers, the Raid Cooldowns window, the Totem Range overlay and the totem assignment window have the new look.",
			"Unlock Bar on the Totem Bar and Cooldown Bar pages: drag the bar from anywhere, no Alt key.",
			"Test Sound buttons next to every sound picker.",
			"The cooldown bar always floats free of the totem bar.",
			"Only the TBC Anniversary client: the Vanilla and Wrath versions are gone.",
		},
		fixes = {
			"Nature's Swiftness, Shamanistic Rage and Bloodlust buttons show when they are active.",
			"Repeated raid cooldown calls from non-shamans are no longer dropped after the first press.",
		},
	},
}
